#!/bin/bash

git clone https://github.com/frozenpandaman/splatnet2statink.git
cat config_template.txt | envsubst > splatnet2statink/config.txt
cd splatnet2statink || exit
pip install -r requirements.txt
python splatnet2statink.py -r
